# Generated by Django 5.2.13 on 2026-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_did', models.CharField(db_index=True, max_length=512)),
                ('credential_type', models.CharField(max_length=128)),
                ('vc_id', models.CharField(max_length=512, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
