# Generated by Django 5.2.13 on 2026-08-24 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, max_length=32)),
                ('discriminator', models.PositiveIntegerField(default=0)),
                ('headline', models.CharField(blank=True, default='', max_length=160)),
                ('default_view', models.CharField(choices=[('deck', 'deck'), ('feed', 'feed')], default='deck', max_length=8)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_deck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=2048)),
                ('icon_category', models.CharField(choices=[('x', 'X'), ('github', 'GitHub'), ('mastodon', 'Mastodon'), ('website', 'Website'), ('blog', 'Blog'), ('talk', 'Talk'), ('poly', 'Poly'), ('gallery', 'Gallery'), ('link', 'Link')], default='link', max_length=20)),
                ('is_ecosystem_link', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.userlinkdeck')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='userlinkdeck',
            constraint=models.UniqueConstraint(fields=('handle', 'discriminator'), name='uniq_handle_disc'),
        ),
    ]
