# Generated by Django 5.2.13 on 2026-08-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userlinkdeck_userlinkitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinkdeck',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlinkdeck',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlinkdeck',
            name='verified_source_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.CreateModel(
            name='HandleVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('target_handle', models.CharField(max_length=32)),
                ('external_url', models.CharField(blank=True, default='', max_length=512)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.userlinkdeck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
