# Generated by Django 5.2.13 on 2026-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_verification_challenge_and_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinkdeck',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='userlinkdeck',
            name='banner_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='userlinkdeck',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userlinkdeck',
            name='lud16',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userlinkdeck',
            name='nip05',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
