# Generated by Django 5.2.13 on 2026-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userlinkdeck_avatar_url_userlinkdeck_banner_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinkdeck',
            name='nostr_pubkey',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
