# Generated by Django 5.2.13 on 2026-09-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userlinkdeck_nostr_pubkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeBlockedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_identifier', models.CharField(db_index=True, help_text='Pubkey hex (64 chars) or DID string to suppress.', max_length=255, unique=True)),
                ('reason', models.CharField(choices=[('ILLEGAL_CSAM', 'Illegal Content'), ('MALWARE', 'Malware'), ('HARASSMENT', 'Severe Harassment'), ('SPAM_BOT', 'Automated Spam'), ('ADMIN_OVERRIDE', 'Operator Emergency Discretion')], default='ADMIN_OVERRIDE', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Node Blocked Entity',
                'verbose_name_plural': 'Node Blocked Entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeContentTakedown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_index=True, help_text='Nostr Event ID (64-hex).', max_length=64, null=True, unique=True)),
                ('media_hash', models.CharField(blank=True, db_index=True, help_text='Blossom media SHA-256 hash (64-hex).', max_length=64, null=True)),
                ('reason', models.CharField(choices=[('ILLEGAL_CSAM', 'Illegal Content'), ('MALWARE', 'Malware'), ('HARASSMENT', 'Severe Harassment'), ('SPAM_BOT', 'Automated Spam'), ('ADMIN_OVERRIDE', 'Operator Emergency Discretion')], default='ADMIN_OVERRIDE', max_length=32)),
                ('purged_from_blossom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Node Content Takedown',
                'verbose_name_plural': 'Node Content Takedowns',
                'ordering': ['-created_at'],
            },
        ),
    ]
