# Generated by Django 5.2.13 on 2026-09-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nodeblockedentity_nodecontenttakedown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationReviewDocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_identifier', models.CharField(db_index=True, help_text='Target Event ID or Author DID/Pubkey.', max_length=255, unique=True)),
                ('docket_type', models.CharField(choices=[('event', 'Nostr Event'), ('pubkey', 'Author Identity')], default='event', max_length=16)),
                ('flag_count', models.PositiveIntegerField(default=1)),
                ('current_tier', models.PositiveSmallIntegerField(default=1, help_text='1=Blur, 2=Suppressed, 3=Quarantined')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('DISMISSED', 'Dismissed by Admin'), ('CONFIRMED', 'Confirmed Action')], default='PENDING', max_length=16)),
                ('reviewed_by_did', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moderation Review Docket',
                'verbose_name_plural': 'Moderation Review Dockets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityFlagLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Target Nostr Event ID (64-hex).', max_length=64)),
                ('target_pubkey', models.CharField(db_index=True, help_text='Target author pubkey hex or DID.', max_length=255)),
                ('reporter_did', models.CharField(db_index=True, help_text='Sovereign DID or pubkey of the reporter.', max_length=255)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam / Flooding'), ('NUDITY_NSFW', 'Unmarked Adult Content'), ('HARASSMENT', 'Abuse / Targeted Harassment'), ('ILLEGAL', 'Illegal / Contraband'), ('MALWARE', 'Malicious Links / Exploits'), ('MISINFO', 'Deceptive Content'), ('OTHER', 'Other Violation')], default='SPAM', max_length=32)),
                ('weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community Flag Ledger',
                'verbose_name_plural': 'Community Flag Ledgers',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('target_event_id', ''), _negated=True), fields=('target_event_id', 'reporter_did'), name='uniq_target_event_reporter_flag')],
            },
        ),
    ]
