# Generated by Django 5.2.13 on 2026-09-18 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_moderationreviewdocket_communityflagledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellant_did', models.CharField(db_index=True, help_text='DID of the author appealing the action', max_length=255)),
                ('statement', models.TextField(help_text="Appellant's restorative statement or explanation")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Operator Review'), ('ACCEPTED', 'Accepted / Friction Cleared'), ('REJECTED', 'Rejected / Action Upheld')], db_index=True, default='PENDING', max_length=16)),
                ('reviewed_by_did', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docket', models.ForeignKey(help_text='Parent review docket under appeal.', on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.moderationreviewdocket')),
            ],
            options={
                'verbose_name': 'Moderation Appeal',
                'verbose_name_plural': 'Moderation Appeals',
                'ordering': ['-created_at'],
            },
        ),
    ]
