# Generated by Django 5.2.13 on 2026-10-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinkitem',
            name='is_verified_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlinkitem',
            name='icon_category',
            field=models.CharField(choices=[('x', 'X'), ('github', 'GitHub'), ('mastodon', 'Mastodon'), ('website', 'Website'), ('blog', 'Blog'), ('talk', 'Talk'), ('poly', 'Poly'), ('gallery', 'Gallery'), ('link', 'Link'), ('email', 'Email')], default='link', max_length=20),
        ),
    ]
