# Copyright (C) 2026 David Byers dba Byers Brands
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("WUN_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("WUN_DEBUG", default=False)

ALLOWED_HOSTS = env.list("WUN_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Session isolation via app prefix
APP_NAME_PREFIX = "wun"

# Cookie Isolation (Prevents collision with IdP on 127.0.0.1)
SESSION_COOKIE_NAME = f"{APP_NAME_PREFIX}_sessionid"
CSRF_COOKIE_NAME = f"{APP_NAME_PREFIX}_csrftoken"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # False for local HTTP development
SESSION_COOKIE_DOMAIN = None
SESSION_SAVE_EVERY_REQUEST = False
CSRF_COOKIE_SECURE = False
SESSION_TRUSTED_ORIGINS = [f"https://{APP_NAME_PREFIX}.iyou.me"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mozilla_django_oidc",  # Keep this!
    "apps.core",  # Your local app
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'mozilla_django_oidc': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'apps.core.auth': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.satellite_urls",
                "apps.core.context_processors.user_identity",
            ],
        },

    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}

if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update({
        "timeout": 20,
        "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
    })


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("es", "Español"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Production static-file compression / fingerprinting via WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Standard User Model
AUTH_USER_MODEL = "auth.User"

# AUTHENTICATION CONFIGURATION
# ------------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'apps.core.auth.MyOIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# iyou_wun uses standard Django users where the 'username' is the DID.
# AUTH_USER_MODEL = 'auth.User' (Standard default)

# OIDC CLIENT (RELYING PARTY) SETTINGS
# ------------------------------------------------------------------------------
# IDP base URLs for endpoint construction
IDP_BASE_INTERNAL_URL = env.str("IDP_BASE_INTERNAL_URL", default="http://127.0.0.1:8000")
IDP_BASE_PUBLIC_URL = env.str("IDP_BASE_PUBLIC_URL", default="https://iyou.me")

# OIDC Relying Party — defaults match ecosystem PKCE public client standard
OIDC_RP_CLIENT_ID = env.str("OIDC_RP_CLIENT_ID", default="iyou-wun-satellite-client")
OIDC_RP_CLIENT_SECRET = env.str("OIDC_RP_CLIENT_SECRET", default="")  # Empty for public PKCE
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_VERIFY_KID = False
OIDC_RP_SCOPES = env.str("OIDC_RP_SCOPES", default="openid profile email")
OIDC_RP_CALLBACK_URL = env.str(
    "OIDC_RP_CALLBACK_URL", default="http://127.0.0.1:8001/oidc/callback/"
)

OIDC_OP_AUTHORIZATION_ENDPOINT = env.str(
    "OIDC_OP_AUTHORIZATION_ENDPOINT",
    default=f"{IDP_BASE_PUBLIC_URL}/openid/authorize/",
)
OIDC_OP_TOKEN_ENDPOINT = env.str(
    "OIDC_OP_TOKEN_ENDPOINT",
    default=f"{IDP_BASE_INTERNAL_URL}/openid/token/",
)
OIDC_OP_USER_ENDPOINT = env.str(
    "OIDC_OP_USER_ENDPOINT",
    default=f"{IDP_BASE_INTERNAL_URL}/openid/userinfo/",
)
OIDC_OP_JWKS_ENDPOINT = env.str(
    "OIDC_OP_JWKS_ENDPOINT",
    default=f"{IDP_BASE_INTERNAL_URL}/openid/jwks/",
)

OIDC_VERIFY_SSL = False
OIDC_STORE_ID_TOKEN = True
OIDC_RP_REQUIRED_CLAIMS = []

# Redirects
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "oidc_authentication_init"

# Required for collectstatic in production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Poly Governance Engine
POLY_ENGINE_URL = env.str("POLY_ENGINE_URL", default="http://127.0.0.1:8000")

# Credential Issuance — Node DID & Signing Key
NODE_DID = env.str("NODE_DID", default="did:key:z6Mkdevlocal00000000000000000000000000000000")
NODE_PRIVATE_KEY_HEX = env.str("NODE_PRIVATE_KEY_HEX", default="")

# Platform administration DID — centralizes env lookup for admin elevation
ADMIN_DID = env.str("ADMIN_DID", default="")

# iyou_home Satellite Service URLs (injected into all template contexts)
IDP_HOME_URL = env.str("IDP_HOME_URL", default="https://home.iyou.me/")
IDP_HOME_WS_URL = env.str("IDP_HOME_WS_URL", default="wss://home.iyou.me:9001/")
BRIDGE_WS_URL = env.str("BRIDGE_WS_URL", default=IDP_HOME_WS_URL)

# Blossom Media Server & CDN Endpoints
BLOSSOM_SERVER_URL = env.str("BLOSSOM_SERVER_URL", default="http://127.0.0.1:9002")
BLOSSOM_CDN_URL = env.str("BLOSSOM_CDN_URL", default="https://cdn.iyou.me")

# XMPP Chat Server — defaults used by context processor; overridden per-level in ChatView
XMPP_DOMAIN = env.str("XMPP_DOMAIN", default="127.0.0.1")
XMPP_WS_URL = env.str("XMPP_WS_URL", default="ws://127.0.0.1:5222")
XMPP_PASSWORD = env.str("XMPP_PASSWORD", default="")

# User infrastructure level: "1" = Managed (cluster), "2" = Sovereign (local enclave)
WUN_USER_LEVEL = env.str("WUN_USER_LEVEL", default="2")

