"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c+jdu#o4x)!=3((fc4$&2b&94%xsbs6izh=p^2q-s4)qfuz-nd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Standard cookie settings for non-HTTPS localhost
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_DOMAIN = None
SESSION_SAVE_EVERY_REQUEST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',  # Keep this!
    'apps.core',            # Your local app
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'apps.core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'mozilla_django_oidc': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Standard User Model
AUTH_USER_MODEL = 'auth.User'

# AUTHENTICATION CONFIGURATION
# ------------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'apps.core.auth.MyOIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# iyou_wun uses standard Django users where the 'username' is the DID.
# AUTH_USER_MODEL = 'auth.User' (Standard default)

# OIDC CLIENT (RELYING PARTY) SETTINGS
# ------------------------------------------------------------------------------
OIDC_RP_SIGN_ALGO = 'RS256'

# Hard-coded OIDC endpoints - force all to use 127.0.0.1 for issuer matching
OIDC_OP_AUTHORIZATION_ENDPOINT = "http://127.0.0.1:8000/openid/authorize/"
OIDC_OP_TOKEN_ENDPOINT = "http://127.0.0.1:8000/openid/token/"
OIDC_OP_USER_ENDPOINT = "http://127.0.0.1:8000/openid/userinfo/"
OIDC_OP_JWKS_ENDPOINT = "http://127.0.0.1:8000/openid/jwks/"
OIDC_RP_SIGN_ALGO = "RS256"

# Temporary SSL verification bypass for development testing
OIDC_VERIFY_SSL = False
OIDC_STORE_ID_TOKEN = True

# Bypass KID verification to isolate signature issues
OIDC_RP_VERIFY_KID = False

# OIDC callback URL - use 127.0.0.1 for consistency
OIDC_RP_CALLBACK_URL = "http://127.0.0.1:8001/oidc/callback/"
# NOTE: No default values here — if these are missing from .env,
# Django will crash with a clear ImproperlyConfigured error.
# Previously had fallback defaults ('wun-client' / 'wun-secret')
# which silently masked broken .env config ("Settings Ghosting").
OIDC_RP_CLIENT_ID = env.str('OIDC_RP_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = env.str('OIDC_RP_CLIENT_SECRET')

OIDC_OP_AUTHORIZATION_ENDPOINT = env.str('OIDC_OP_AUTHORIZATION_ENDPOINT')
OIDC_OP_TOKEN_ENDPOINT = env.str('OIDC_OP_TOKEN_ENDPOINT')
OIDC_OP_USER_ENDPOINT = env.str('OIDC_OP_USER_ENDPOINT')
OIDC_OP_JWKS_ENDPOINT = env.str('OIDC_OP_JWKS_ENDPOINT')

# Redirects
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'oidc_authentication_init'

# This ensures the 'sub' (the DID) from the IdP is used as the local username
OIDC_USERNAME_ALGO = lambda claims: claims.get('sub')

# Debug print to verify environment loading
print(f"DEBUG: Auth Endpoint is {OIDC_OP_AUTHORIZATION_ENDPOINT}")
print(f"DEBUG: Token Endpoint is {OIDC_OP_TOKEN_ENDPOINT}")
print(f"DEBUG: User Endpoint is {OIDC_OP_USER_ENDPOINT}")
print(f"DEBUG: JWKS Endpoint is {OIDC_OP_JWKS_ENDPOINT}")
